#:kivy 1.0

<Files>:
    id:select_path_panel
    orientation: 'vertical'
    BoxLayout:
        Label:
            text:"Please select an images file or folder by click following button"
    BoxLayout:
        size_hint_y:None
        height:dp(40)
        Button:
            text: 'File'
            on_release: root.open_file()
        Button:
            text: 'Folder'
            on_release: root.open_folder()
